name: run tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install -r requirements.txt
      - run: python test.py
      - uses: actions/upload-artifact@v2
        with:
          path: results/*
